name: R21 Data Pipeline

permissions:
  contents: write

on:
  workflow_dispatch:
  schedule:
    - cron: '0 5 * * *'

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests snowflake-connector-python cryptography pandas

      - name: Run ETL
        run: python fetch_r21_data.py
